-- --------------------------------------------------------
-- Hostitel:                     127.0.0.1
-- Verze serveru:                8.0.32 - MySQL Community Server - GPL
-- OS serveru:                   Linux
-- HeidiSQL Verze:               12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Exportování struktury pro tabulka nubium.articles
CREATE TABLE IF NOT EXISTS `articles` (
  `article_id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `perex` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `text` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `visible` tinyint NOT NULL DEFAULT '0',
  `private` tinyint NOT NULL DEFAULT '0',
  `rating` int NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `published` datetime NOT NULL,
  PRIMARY KEY (`article_id`),
  KEY `FK__users` (`user_id`),
  CONSTRAINT `FK__users` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Exportování dat pro tabulku nubium.articles: ~20 rows (přibližně)
INSERT INTO `articles` (`article_id`, `user_id`, `title`, `perex`, `text`, `visible`, `private`, `rating`, `created`, `published`) VALUES
	(1, 1, 'test 1', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Suspendisse sagittis ultrices augue. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Aliquam ornare wisi eu metus. Fusce consectetuer risus a nunc. Curabitur vitae diam non enim vestibulum interdum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Sed convallis magna eu sem. Maecenas lorem. Vivamus luctus egestas leo. In rutrum. Nam quis nulla.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 1, '2023-02-23 11:46:36', '2023-02-23 11:00:00'),
	(2, 1, 'test 2', 'Aliquam erat volutpat. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla pulvinar eleifend sem. Integer pellentesque quam vel velit. Praesent id justo in neque elementum ultrices. Morbi scelerisque luctus velit. Nulla pulvinar eleifend sem. Nulla non arcu lacinia neque faucibus fringilla. Aliquam erat volutpat. Nullam faucibus mi quis velit. Duis risus. Curabitur bibendum justo non orci. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Suspendisse nisl.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 1, '2023-02-23 11:46:36', '2023-02-23 11:05:00'),
	(3, 1, 'test 3', 'Aliquam in lorem sit amet leo accumsan lacinia. Aliquam ornare wisi eu metus. Vestibulum fermentum tortor id mi. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Nullam dapibus fermentum ipsum. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Aliquam erat volutpat. In dapibus augue non sapien. Pellentesque arcu. Vivamus ac leo pretium faucibus. Proin in tellus sit amet nibh dignissim sagittis. Suspendisse nisl. Integer malesuada. Aenean id metus id velit ullamcorper pulvinar.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:10:00'),
	(4, 1, 'test 4', 'Nullam at arcu a est sollicitudin euismod. Maecenas aliquet accumsan leo. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Aenean placerat. Etiam bibendum elit eget erat. Sed convallis magna eu sem. Duis viverra diam non justo. Pellentesque sapien. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam posuere lacus quis dolor. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Etiam posuere lacus quis dolor. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. In convallis.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:15:00'),
	(5, 1, 'test 5', 'Vivamus luctus egestas leo. Aliquam erat volutpat. Maecenas lorem. Donec quis nibh at felis congue commodo. Curabitur vitae diam non enim vestibulum interdum. Aenean id metus id velit ullamcorper pulvinar. Donec quis nibh at felis congue commodo. Mauris dictum facilisis augue. Pellentesque ipsum. Praesent in mauris eu tortor porttitor accumsan. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Fusce wisi. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Vivamus porttitor turpis ac leo.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:20:00'),
	(6, 1, 'test 6', 'Integer vulputate sem a nibh rutrum consequat. In rutrum. Phasellus rhoncus. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Pellentesque sapien. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Proin mattis lacinia justo. Integer tempor. Mauris dictum facilisis augue. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Duis risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:25:00'),
	(7, 1, 'test 7', 'Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Integer vulputate sem a nibh rutrum consequat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Donec vitae arcu. Integer tempor. Phasellus et lorem id felis nonummy placerat. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nunc auctor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Praesent id justo in neque elementum ultrices.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:30:00'),
	(8, 1, 'test 8', 'Cras elementum. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. In dapibus augue non sapien. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Phasellus rhoncus. Integer imperdiet lectus quis justo. Praesent id justo in neque elementum ultrices. Mauris tincidunt sem sed arcu. Etiam neque. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Nam sed tellus id magna elementum tincidunt. Nulla non lectus sed nisl molestie malesuada. Duis pulvinar. Proin mattis lacinia justo. Vivamus luctus egestas leo. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nullam faucibus mi quis velit. Nullam eget nisl. Duis risus.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:35:00'),
	(9, 1, 'test 9', 'Etiam quis quam. Etiam dictum tincidunt diam. Praesent id justo in neque elementum ultrices. Nullam dapibus fermentum ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Aliquam erat volutpat. Aliquam erat volutpat. Maecenas aliquet accumsan leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Praesent in mauris eu tortor porttitor accumsan. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Etiam egestas wisi a erat. Aenean vel massa quis mauris vehicula lacinia. Praesent id justo in neque elementum ultrices. Donec quis nibh at felis congue commodo.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:40:00'),
	(10, 1, 'test 10', 'Fusce tellus. Etiam commodo dui eget wisi. Duis viverra diam non justo. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Nullam eget nisl. Integer vulputate sem a nibh rutrum consequat. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Praesent in mauris eu tortor porttitor accumsan. Aliquam id dolor. Fusce tellus. Morbi scelerisque luctus velit. Vestibulum fermentum tortor id mi. Proin in tellus sit amet nibh dignissim sagittis. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, -1, '2023-02-23 11:46:36', '2023-02-23 11:45:00'),
	(11, 1, 'test 11', 'Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec quis nibh at felis congue commodo. Vivamus porttitor turpis ac leo. Ut tempus purus at lorem. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nullam rhoncus aliquam metus. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Mauris tincidunt sem sed arcu. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Integer pellentesque quam vel velit. Etiam egestas wisi a erat. Pellentesque arcu. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(12, 1, 'test 12', 'Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Praesent in mauris eu tortor porttitor accumsan. Nam quis nulla. Fusce suscipit libero eget elit. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Phasellus et lorem id felis nonummy placerat. Integer imperdiet lectus quis justo. Nulla est. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(13, 1, 'test 13', 'Fusce wisi. Proin in tellus sit amet nibh dignissim sagittis. Integer lacinia. Aliquam ornare wisi eu metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Maecenas aliquet accumsan leo. Fusce aliquam vestibulum ipsum. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Aenean placerat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer vulputate sem a nibh rutrum consequat. Duis condimentum augue id magna semper rutrum. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Etiam dictum tincidunt diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer malesuada. Etiam quis quam. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(14, 1, 'test 14', 'Etiam bibendum elit eget erat. Fusce nibh. Vivamus luctus egestas leo. Pellentesque arcu. Nullam at arcu a est sollicitudin euismod. Duis risus. Nullam sit amet magna in magna gravida vehicula. Nunc tincidunt ante vitae massa. Nulla non lectus sed nisl molestie malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla non arcu lacinia neque faucibus fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(15, 1, 'test 15', 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. In convallis. Duis pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Aenean vel massa quis mauris vehicula lacinia. Fusce nibh. Etiam neque. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Vivamus porttitor turpis ac leo. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Donec iaculis gravida nulla. Morbi scelerisque luctus velit. Aliquam erat volutpat. Nulla pulvinar eleifend sem. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Nam sed tellus id magna elementum tincidunt. Integer vulputate sem a nibh rutrum consequat.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(16, 1, 'test 16', 'Mauris dictum facilisis augue. Quisque tincidunt scelerisque libero. Integer vulputate sem a nibh rutrum consequat. Etiam neque. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Duis risus. Aenean fermentum risus id tortor. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Aliquam erat volutpat. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Mauris elementum mauris vitae tortor. Duis condimentum augue id magna semper rutrum. In rutrum. Nullam eget nisl. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Praesent dapibus. Curabitur vitae diam non enim vestibulum interdum.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(17, 1, 'test 17', 'Praesent id justo in neque elementum ultrices. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Duis viverra diam non justo. Proin mattis lacinia justo. Nam quis nulla. Maecenas sollicitudin. Integer imperdiet lectus quis justo. Fusce tellus. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Phasellus rhoncus. Aliquam in lorem sit amet leo accumsan lacinia. Et harum quidem rerum facilis est et expedita distinctio. Phasellus faucibus molestie nisl. In convallis. Donec quis nibh at felis congue commodo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nulla pulvinar eleifend sem.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(18, 1, 'test 18', 'Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Nulla non arcu lacinia neque faucibus fringilla. Nullam faucibus mi quis velit. Nunc dapibus tortor vel mi dapibus sollicitudin. Duis condimentum augue id magna semper rutrum. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Curabitur sagittis hendrerit ante. Suspendisse sagittis ultrices augue. Mauris dictum facilisis augue. Etiam commodo dui eget wisi. Vivamus luctus egestas leo. Fusce aliquam vestibulum ipsum. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Pellentesque ipsum. Mauris tincidunt sem sed arcu. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(19, 1, 'test 19', 'Integer tempor. Fusce aliquam vestibulum ipsum. Aliquam erat volutpat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nullam faucibus mi quis velit. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Phasellus faucibus molestie nisl. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 1, 0, '2023-02-23 11:46:36', '2023-02-23 11:46:37'),
	(20, 1, 'test 20', 'Curabitur bibendum justo non orci. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Vestibulum erat nulla, ullamcorper nec, rutrum non, nonummy ac, erat. Mauris metus. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Nullam rhoncus aliquam metus. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Nam sed tellus id magna elementum tincidunt. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Donec iaculis gravida nulla.', 'Curabitur sagittis hendrerit ante. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Sed ac dolor sit amet purus malesuada congue. Vestibulum fermentum tortor id mi. Maecenas libero. Donec iaculis gravida nulla. Mauris tincidunt sem sed arcu. Nulla pulvinar eleifend sem. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis.', 1, 0, 0, '2023-02-23 11:46:36', '2025-01-01 00:00:00');

-- Exportování struktury pro tabulka nubium.article_rating
CREATE TABLE IF NOT EXISTS `article_rating` (
  `article_id` int unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `rating` int NOT NULL,
  `date` datetime NOT NULL,
  `ipaddr` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  UNIQUE KEY `article_id_user_id` (`article_id`,`user_id`),
  KEY `FK__articles` (`article_id`),
  KEY `FK__ratingusers` (`user_id`),
  CONSTRAINT `FK__articles` FOREIGN KEY (`article_id`) REFERENCES `articles` (`article_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK__ratingusers` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Exportování dat pro tabulku nubium.article_rating: ~3 rows (přibližně)
INSERT INTO `article_rating` (`article_id`, `user_id`, `rating`, `date`, `ipaddr`) VALUES
	(1, 1, 1, '2023-02-25 10:21:09', '192.168.0.1'),
	(2, 1, 1, '2023-02-24 11:30:51', '127.0.0.1'),
	(10, 1, -1, '2023-02-25 10:20:58', '192.168.0.1');

-- Exportování struktury pro tabulka nubium.users
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ipaddr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `reg_date` datetime NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Exportování dat pro tabulku nubium.users: ~2 rows (přibližně)
INSERT INTO `users` (`user_id`, `name`, `email`, `password`, `ipaddr`, `reg_date`) VALUES
	(1, 'admin', 'admin@nubium-sandbox.test', '$2y$10$k92XBFQ6ItWR1bJQSGFWRuIU5Z0eDN06BAvuoglInmrgVaJrb6n.6', '127.0.0.1', '2023-02-23 11:45:33');

-- Exportování struktury pro trigger nubium.article_rating_after_delete
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `article_rating_after_delete` AFTER DELETE ON `article_rating` FOR EACH ROW BEGIN
	UPDATE `articles` A SET A.`rating`=(SELECT IFNULL(SUM(AR.rating), 0) FROM `article_rating` AR WHERE AR.`article_id`=A.`article_id`) WHERE A.`article_id`=OLD.`article_id`;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Exportování struktury pro trigger nubium.article_rating_after_insert
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `article_rating_after_insert` AFTER INSERT ON `article_rating` FOR EACH ROW BEGIN
	UPDATE `articles` A SET A.`rating`=(SELECT IFNULL(SUM(AR.rating), 0) FROM `article_rating` AR WHERE AR.`article_id`=A.`article_id`) WHERE A.`article_id`=NEW.article_id;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Exportování struktury pro trigger nubium.article_rating_after_update
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `article_rating_after_update` AFTER UPDATE ON `article_rating` FOR EACH ROW BEGIN
	UPDATE `articles` A SET A.`rating`=(SELECT IFNULL(SUM(AR.rating), 0) FROM `article_rating` AR WHERE AR.`article_id`=A.`article_id`) WHERE A.`article_id`=NEW.article_id OR A.`article_id`=OLD.`article_id`;
END//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
